//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferExcelByElectric.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransferExcelByElectric.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开    始 的本地化字符串。
        /// </summary>
        internal static string btn_startend {
            get {
                return ResourceManager.GetString("btn_startend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂    停 的本地化字符串。
        /// </summary>
        internal static string btn_startend_stop {
            get {
                return ResourceManager.GetString("btn_startend_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ?phone={0}&amp;customer_no={1}&amp;name={2}&amp;date={3}&amp;email={4} 的本地化字符串。
        /// </summary>
        internal static string send_port_template {
            get {
                return ResourceManager.GetString("send_port_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认关闭系统，请确认系统没有在执行的任务。 的本地化字符串。
        /// </summary>
        internal static string str_closesys {
            get {
                return ResourceManager.GetString("str_closesys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭系统 的本地化字符串。
        /// </summary>
        internal static string str_closesys_title {
            get {
                return ResourceManager.GetString("str_closesys_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件失败，请确认程序目录下的\\DB文件夹中存在名为elecon.ini文件，并正确配置！ 的本地化字符串。
        /// </summary>
        internal static string str_errconfigfile {
            get {
                return ResourceManager.GetString("str_errconfigfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统文件缺失 的本地化字符串。
        /// </summary>
        internal static string str_errconfigfile_title {
            get {
                return ResourceManager.GetString("str_errconfigfile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用数据源文件名错误！ 的本地化字符串。
        /// </summary>
        internal static string str_errexcelname {
            get {
                return ResourceManager.GetString("str_errexcelname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统文件错误 的本地化字符串。
        /// </summary>
        internal static string str_errexcelname_title {
            get {
                return ResourceManager.GetString("str_errexcelname_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用数据源文件出错！ 的本地化字符串。
        /// </summary>
        internal static string str_errloadexcel {
            get {
                return ResourceManager.GetString("str_errloadexcel", resourceCulture);
            }
        }
    }
}
